// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: get_feeds_with_creator.sql

package database

import (
	"context"
)

const getFeedsWithCreator = `-- name: GetFeedsWithCreator :many
SELECT
  feeds.name,
  feeds.url,
  users.name AS username
FROM feeds
JOIN users ON users.id = feeds.user_id
ORDER BY feeds.created_at
`

type GetFeedsWithCreatorRow struct {
	Name     string
	Url      string
	Username string
}

func (q *Queries) GetFeedsWithCreator(ctx context.Context) ([]GetFeedsWithCreatorRow, error) {
	rows, err := q.db.QueryContext(ctx, getFeedsWithCreator)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFeedsWithCreatorRow
	for rows.Next() {
		var i GetFeedsWithCreatorRow
		if err := rows.Scan(&i.Name, &i.Url, &i.Username); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
